### ISSUE TITLE
`doc_comment` does not work on enum variants and struct fields

### ISSUE THREAD

**Issue by ensko** [GuillaumeGomez/doc-comment#13]
```
use doc_comment::doc_comment;

pub enum Foo1 {
    doc_comment!(
        "doc",
        Bar
    )
}

pub struct Foo2 {
    doc_comment!(
        "doc",
        pub Bar: u32
    )
}
```

Title says it all. I think this can't be fixed, but if it can by any chance, here's the report.

**Comment by GuillaumeGomez** [comment]
I'll take a look. Thanks for reporting the issue!

**Comment by GuillaumeGomez** [comment]
We could by having the full type declaration inside it. For example:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=103ed000b91a6a98b1a27a4ba8312f7a

And this post too: https://stackoverflow.com/a/37007315

**Comment by GuillaumeGomez** [comment]
I switched to proc-macros in #21, so it's now possible! I'll make the new release soon.
