### ISSUE TITLE
Skip/Exclude code block while checking

### ISSUE THREAD

**Issue by mre** [GuillaumeGomez/doc-comment#26]
Is there a way to skip a code block in the `README.md` while checking?

I have a snippet for a builder struct in my docs:

```rust
let client = lychee::ClientBuilder::default()
    .includes(includes)
    .excludes(excludes)
    .build()?;
 ```

The snippets contains undefined variables, but in this case I'd like to skip it because I explain the usage of the builder above this snippet and in the docs. 
I could mark it as `sh` for example, which skips the check, but it also skips the pretty Github syntax highlighting. Any other way?

**Comment by GuillaumeGomez** [comment]
Like this I guess:

    ```rust,ignore
