### ISSUE TITLE
Locating doctests in outer markdown files

### ISSUE THREAD

**Issue by Alexander-N** [GuillaumeGomez/doc-comment#8]
If there are multiple outer markdown Files its difficult to tell in which file to look for a failing test.

For example

```rust
doctest!("../book/chapter1.md");
doctest!("../book/chapter2.md");
```
could give me

```
test <::doc_comment::doc_comment macros> -  (line 335) ... FAILED
test <::doc_comment::doc_comment macros> -  (line 207) ... ok
test <::doc_comment::doc_comment macros> -  (line 359) ... FAILED
test <::doc_comment::doc_comment macros> -  (line 550) ... ok
```
This gives no indication where the doctests are located since the line numbers do not correspond to the `doctest!` lines.

Ideally the output would be something like
```
test book/chapter1.md - ExampleSection1::Header3 - (line 52) ... FAILED
test book/chapter1.md - ExampleSection1::Header4 - (line 100) ... ok
test book/chapter2.md - ExampleSection2::Header1 - (line 99) ... FAILED
test book/chapter2.md - ExampleSection2::Header2 - (line 199) ... ok
```

**Comment by GuillaumeGomez** [comment]
It's rustdoc which generates this output. It might be possible to improve its output a bit by generating modules with a given name maybe? To be checked.

**Comment by Alexander-N** [comment]
It would be a great help if a name which contains the file name could be used.

I'm thinking of
```
test <::doc_comment::doc_comment macros> - book_chapter1 (line 335) ... FAILED
```

**Comment by GuillaumeGomez** [comment]
I'm thinking of allowing users to pass a second argument to the macro which will be the name of the item on which the doc will be. Like I said, to be tested further.
